### ISSUE TITLE
Can't compile

### ISSUE THREAD

**Issue by zhaomy163** [cmatsuoka/amibios_dmi#1]
when compile can't find amibios_dmi.c file.
How to get amibios_dmi.c for compile?

**Comment by cmatsuoka** [comment]
By default, it looks for the kernel source tree using the `/lib/modules/<version>/build` symlink, but you can also specify it manually overriding the KERNEL variable used in the Makefile.

I just tested it in a reasonably updated system running Ubuntu and it built correctly:

```
$ make
make -C /lib/modules/4.13.0-32-generic/build SUBDIRS=/home/claudio/amibios_dmi modules
make[1]: Entering directory '/usr/src/linux-headers-4.13.0-32-generic'
  CC [M]  /home/claudio/amibios_dmi/amibios_smi.o
  CC [M]  /home/claudio/amibios_dmi/amibios_sysfs.o
  LD [M]  /home/claudio/amibios_dmi/amibios_dmi.o
  Building modules, stage 2.
  MODPOST 1 modules
  CC      /home/claudio/amibios_dmi/amibios_dmi.mod.o
  LD [M]  /home/claudio/amibios_dmi/amibios_dmi.ko
```

But I can't say for sure if it still works, I don't have a system with this BIOS anymore.

**Comment by zhaomy163** [comment]
Hi Claudio:
  Let me express sincere gratitude to your help,we compiled OK and prepare to test.
BR!
Meiyu

**Comment by cmatsuoka** [comment]
Thank you, please let me know if it still works.
